export const INITIALIZATION = 'INITIALIZATION';
export const UPDATE_MEETUP_DATA = 'UPDATE_MEETUP_DATA';
export const ADD_FAVORITE_EVENT = 'ADD_FAVORITE_EVENT';
export const DELETE_FAVORITE_EVENT = 'DELETE_FAVORITE_EVENT';
